### ISSUE TITLE
Ignore commands that start with a space

### ISSUE THREAD

**Issue by sbrl** [rcaloras/bashhub-client#91] opened 2020-10-02 14:00 UTC
In Bash, If one starts a command with a space it doesn't get saved to the `~/.bash_history` file. While I'm aware of `bashhub off` and `bashhub on`, it's an extra step that I may easily forget.

Is there a way to get the bashhub client to ignore  all commands that  start with a space?

**Comment by rcaloras** [comment] 2020-10-02 16:21
Hey @sbrl, you should be able to use https://github.com/rcaloras/bashhub-client#filtering-commands to filter out anything based on a regex. You can also append `#ignore` on any command. 

As an FYI, [bash-preexec](https://github.com/rcaloras/bash-preexec) is used, if you're using bashhub with bash, and changes the history control to disallow ignore spacing by bash.

**Comment by sbrl** [comment] 2020-10-02 20:37
Wow, I was not aware that bashhub changed by preference. How do I change it back?

I see. Could I do something like this then?

```bash
export BH_FILTER="^\s+"
```

**Comment by rcaloras** [comment] 2020-10-02 20:54
> I see. Could I do something like this then?

Yes, you can check it with the `bashhub filter` command:

```
[rcaloras:~/git/bashhub-client] master 4d18h58m39s ± bashhub filter --help
Usage: bashhub filter [OPTIONS] COMMAND

  Check if a command is filtered from bashhub. Filtering is configured via a
  regex exported as BH_FILTER.

  BH_FILTER is unset.

Options:
  -r, --regex TEXT  Regex to filter against
  -h, --help        Show this message and exit.
```

**Comment by rcaloras** [comment] 2020-10-02 20:56
> Wow, I was not aware that bashhub changed my preference. How do I change it back?

You can move any histcontol setup you have after bashhub's profile hook. e.g. `export HISTCONTROL=ignoredups`

Although doing this may cause bash-preexec to not work as intended in some edge cases.

**Comment by rcaloras** [comment] 2020-10-02 21:03
@sbrl I actually just put in config support for filtering (https://github.com/rcaloras/bashhub-client/commit/0bcc223d11f363f22b8ac1aef9e399428660dd41). Meant to do this a while ago. If you `bashhub update` to `2.1.1` you can configure your filter in your ~/.bashhub/config too.

**Comment by rcaloras** [comment] 2020-10-07 00:20
closing. Feel free to reopen if needed.

**Closed by rcaloras** 2020-10-07 00:20 UTC
