### ISSUE TITLE
Any Bashub search takes about 3 seconds

### ISSUE THREAD

**Issue by curusarn** [rcaloras/bashhub-client#79] opened 2020-04-19 17:58 UTC
I just installed Bashub and every search takes about 3 seconds.

I tried this multiple times with very similar results:
```
[simon@tower ~]$ time bh xxxx
time bh xxxx

real	0m3.298s
user	0m0.156s
sys	0m0.080s
```

To see if there is a significant delay caused by the request processing on the server I tried to simply download the bashhub homepage (multiple times with similar results):
```
❯ time curl bashhub.com > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0     64      0  0:00:02  0:00:02 --:--:--    64
curl bashhub.com > /dev/null  0.00s user 0.01s system 0% cpu 2.775 total
```

It seems that most of the delay is caused by transit and not by request processing.

Is this expected? Could this be related to where you are hosting the server?

**Comment by rcaloras** [comment] 2020-05-20 01:06
@curusarn thanks for the feedback and apologies for the delayed response!
This shouldn't be expected, but may be caused by transit. The hosting is in North America East region. Not sure where you're connecting from.

Running a few queries as examples:
```
[rcaloras:~] $ time bh "echo" > /dev/null
real	0m0.562s
user	0m0.223s
sys	0m0.067s

[rcaloras:~] $ time curl bashhub.com > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   2421      0 --:--:-- --:--:-- --:--:--  2438

real	0m0.095s
user	0m0.010s
sys	0m0.013s
```

**Comment by rcaloras** [comment] 2020-05-24 03:02
Closing. Feel free to comment or reopen for further support or if you something seems broken.

**Closed by rcaloras** 2020-05-24 03:02 UTC
